spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      stat-view-servlet:
        login-username: admin
        login-password: admin